### ISSUE TITLE
Sign Up process

### ISSUE THREAD

**Issue by Mindo-Joseph** [andrewkimjoseph/plpfinalproject#1]
- How do I sign up?

**Comment by andrewkimjoseph** [comment]
Well, you don't. You create an account for an agent in the client area. But I can give you test logins.

If you continue as admin:
ID: root
PASSWORD: tap the space bar once (the password is a single space bar)

If you continue as client:
ID: saapp_001
PASSWORD: 0000

If you continue as agent:
CLIENT ID: 100
ID: pcl_001
PASSWORD: 0000

**Comment by Mindo-Joseph** [comment]
Ok lemme try it 😎

**Comment by Mindo-Joseph** [comment]
It worked

**Comment by Mindo-Joseph** [comment]
This code creates a list of MyData objects for the years 2020, 2021, and 2022, and passes it to the MyChart widget. The MyChart widget then uses this data to render the line chart showing the changes in the principle over time
